<?php
$this->title = "My Albums";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'add'));?>">Add new album</a></p>

<table>
<tr>
    <th>Id</th>
    <th>Title</th>
    <th>Artist</th>
    <th>& </th>
</tr>

<?php foreach($this->result as $album => $val) : ?>

<tr>
    <td><?php echo $this->escape($val['id']);?></td>
    <td><?php echo $this->escape($val['title']);?></td>
    <td><?php echo $this->escape($val['artist']);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'index', 
                                             'action'=>'edit',
                                             'id'=>$val['id']));
                ?>">Edit</a>
        <a href="<?php echo $this->url(array('controller'=>'index', 
                                             'action'=>'delete',
                                             'id'=>$val['id']));
                ?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
